# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2014-09-28 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null='FALSE')),
                ('password', models.CharField(max_length=250, null='FALSE')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250, null='FALSE')),
                ('password', models.CharField(max_length=250, null='FALSE')),
                ('homeadd', models.CharField(max_length=250, null='FALSE')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(null='FALSE')),
                ('product_id', models.IntegerField(null='FALSE')),
                ('product_name', models.CharField(max_length=250, null='FALSE')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=250, null='FALSE')),
                ('product_type', models.CharField(max_length=250, null='FALSE')),
                ('quantity', models.IntegerField(null='FALSE')),
                ('time', models.TimeField(max_length=250, null='FALSE')),
                ('date', models.DateField(max_length=250, null='FALSE')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.IntegerField(null='FALSE')),
                ('product_id', models.IntegerField(null='FALSE')),
                ('quantity', models.IntegerField(null='FALSE')),
                ('time', models.TimeField(max_length=250, null='FALSE')),
                ('date', models.DateField(max_length=250, null='FALSE')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, null='FALSE')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=250, null='FALSE')),
                ('product_type', models.CharField(max_length=250, null='FALSE')),
            ],
        ),
    ]
