# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2014-09-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=250, null='FALSE'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=250, null='FALSE'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(max_length=250, null='FALSE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='clientid',
            field=models.CharField(max_length=250, null='FALSE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.CharField(max_length=250, null='FALSE'),
        ),
    ]
