# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2014-09-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0002_auto_20140928_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='quantity',
            field=models.CharField(max_length=250, null='FALSE'),
        ),
    ]
