# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2014-09-28 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstractApp', '0006_auto_20140928_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='history',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='history',
            name='product_type',
        ),
    ]
